#!/bin/bash
  

case "$1" in

stopped)  echo -e  "\n\n\t\t\t\t\t\t\tListing Vm's in stopped state"

aws ec2 describe-instances --query 'Reservations[*].Instances[*].{Name:Tags[?Key==`Name`]|[0].Value,InstanceID:InstanceId,AZ:Placement.AvailabilityZone,InstanceState:State.Name,Instancetype:InstanceType,SubnetID:SubnetId,VPCId:VpcId,privateip:PrivateIpAddress}' --filters Name=instance-state-name,Values=stopped --output table

    ;;
stopped-tag)

echo -ne "\nEnter the Tag Name:"
read NAME
echo -n "Enter the Tag Value:"
read VALUE

aws ec2 describe-instances --query 'Reservations[*].Instances[*].{Name:Tags[?Key==`Name`]|[0].Value,InstanceID:InstanceId,AZ:Placement.AvailabilityZone,InstanceState:State.Name,Instancetype:InstanceType,SubnetID:SubnetId,VPCId:VpcId,privateip:PrivateIpAddress}' --filter "Name=instance-state-name,Values=stopped" "Name=tag:$NAME,Values=$VALUE" --output table

Total=`aws ec2 describe-instances --query 'Reservations[*].Instances[*].{InstanceID:InstanceId}' --filter "Name=instance-state-name,Values=stopped" "Name=tag:$NAME,Values=$VALUE" --output text | wc -l`

echo -e "\nInstance_Count - $Total"

    ;;
delete-tag)  

echo -ne "\nEnter the Tag Name:"
read NAME
echo -n "Enter the Tag Value:"
read VALUE

Total=`aws ec2 describe-instances --query 'Reservations[*].Instances[*].{InstanceID:InstanceId}' --filter "Name=instance-state-name,Values=stopped" "Name=tag:$NAME,Values=$VALUE" --output text | wc -l`

if [[ $Total -eq 0 ]]
then 
  echo -e "\n0 Instance Found, None of the Instances have associated tags "Name=$NAME",Value="$VALUE" Aborting the Job!!"
else

echo -e "\nInstance_Delete_Count - $Total"

while true; do
    echo -e "\nInstances to be Terminated:\n"

aws ec2 describe-instances --query 'Reservations[*].Instances[*].{Name:Tags[?Key==`Name`]|[0].Value,InstanceID:InstanceId,AZ:Placement.AvailabilityZone,InstanceState:State.Name,Instancetype:InstanceType,SubnetID:SubnetId,VPCId:VpcId,privateip:PrivateIpAddress}' --filter "Name=instance-state-name,Values=stopped" "Name=tag:$NAME,Values=$VALUE" --output table

    read -p "Are you sure you want to terminate these instances?" yn
    case $yn in
        [Yy]* )

aws ec2 describe-instances --query 'Reservations[*].Instances[*].{InstanceID:InstanceId}' --filter "Name=instance-state-name,Values=stopped" "Name=tag:$NAME,Values=$VALUE" --output text | xargs aws ec2 terminate-instances --instance-ids  1> /dev/null && echo -e "\nTerminating the Instances" && exit

        ;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done


fi

;;
*)
echo -e "\nPlease choose from the given options:-"
echo -e  "\n* stopped - List EC2 Instances in Stopped state"
echo -e  "\n* stopped-tag - List EC2 Instances in Stopped state with specific tags"
echo -e  "\n* delete-tag - delete EC2 Instances in Stopped state with specific tags"
echo -e "\e[92m\nExample : ./getvmstat stopped\e[0m"

   ;;
esac
                              
